# Extra resources {-}

Analyzing NGS data can be a complex process, especially with the rise of 
multi-omics approaches. Here is a list of resources we thought would be 
useful for people interested in going deeper in the analysis of NGS data. 

## General bioinformatics 

- A comprehensive overview of the different types of bioinformatic analyses, divided in 4 fundamental modules: [LINK](https://liulab-dfci.github.io/bioinfo-combio/)

## R/Bioconductor 

- ***The*** excellent R guide for beginners, by Emmanuel Paradis: [PDF](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf)
- ***The*** 150+ pages comprehensive book to learn everything about Bioconductor. This ebook has been published by [Kasper D. Hansen](https://www.ashansenlab.com/) and is freely available under the [CC BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US): [Link to EPUB](https://leanpub.com/bioconductor)

## Scientific readings

- [2014 Nat. Methods paper from Bioconductor core team describing important object classes](https://www.nature.com/articles/nmeth.3252)
- [To see from how far Bioc comes from\.\.\.](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2004-5-10-r80)
